### ISSUE TITLE
Random cursor blinks when zoom-mode enabled

### ISSUE THREAD

**Issue by averrin** [cyrus-and/zoom#10]
When zoom-mode enabled i see random cursor and text blinks.
When i disable it, everything is ok.

**Comment by cyrus-and** [comment]
You need to give me more details, how can I reproduce this? Possibly start from `emacs -Q`.

**Comment by averrin** [comment]
I cannot reproduce it after emacs restart.

**Comment by cyrus-and** [comment]
Feel free to add details if it happens again.
