### ISSUE TITLE
Interacts badly with beacon

### ISSUE THREAD

**Issue by indigoviolet** [cyrus-and/zoom#12]
Do you happen to know why this might make https://github.com/Malabarba/beacon much more stutter-y?

**Comment by cyrus-and** [comment]
Everything seems to work fine with beacon here. When/where do you experience this?

**Comment by cyrus-and** [comment]
Bump.

**Comment by indigoviolet** [comment]
I'm no longer convinced this was zoom/beacon alone. Changing `jit-lock-defer-time`  improved it.
