### ISSUE TITLE
Occupying memory when typing continuously

### ISSUE THREAD

**Issue by blue0513** [cyrus-and/zoom#13]
Hi! Thanks for treating [this issue](https://github.com/cyrus-and/zoom/issues/5) before!

I have a question about Memory Usage.

When I split two buffers and input characters continuously, the operation is **very heavy** as bellow (keep pressing `a` in this example)

![untitled4](https://user-images.githubusercontent.com/8979468/32542390-c6eabcce-c4b5-11e7-8df3-36e06069e773.gif)

And I got a Profiler-report (`M-x profiler-report`)

```lisp
- redisplay_internal (C function)                       2,263,433,900  94%
 - zoom--handler                                        2,229,488,180  93%
  - zoom--update                                        2,229,449,108  93%
   - balance-windows                                    1,186,711,412  49%
    - apply                                             1,186,711,412  49%
     - ad-Advice-balance-windows                        1,186,711,412  49%
      + #<compiled 0x4009ec51>                          1,186,711,412  49%
   - zoom--resize                                       1,042,575,784  43%
    - zoom--resize-one-dimension                        1,042,569,400  43%
     - window-resize                                    1,041,707,832  43%
      + window--resize-siblings                             1,579,432   0%
      + run-window-configuration-change-hook                  358,484   0%
      + window--resizable-p                                    23,232   0%
       frame-height                                           429,720   0%
       frame-width                                            414,952   0%
     + window-resizable                                        16,896   0%
     zoom--window-ignored-p                                   161,912   0%
  + #<compiled 0x44947517>                                     11,616   0%
 + eval                                                    33,058,980   1%
 + jit-lock-function                                          554,568   0%
 + keymap-canonicalize                                        131,040   0%
 + page-break-lines--update-display-tables                     81,312   0%
 + menu-bar-update-buffers                                     31,316   0%
 + #<compiled 0x40c13c45>                                      19,008   0%
   file-remote-p                                                5,120   0%
   undo-tree-update-menu-bar                                    2,112   0%

```

Do you know the reason why `zoom--handler` occupies memory a lot ?

**Comment by cyrus-and** [comment]
Wow that's impressive 2GB... I don't experience that. Can you try to reproduce it with `emacs -Q` then installing zoom? I suspect there is some interference going on.

Also can you send me the whole report? (In the profile buffer hit `C-x C-w`.)

**Comment by blue0513** [comment]
@cyrus-and I did it, and got this.... (without any **heavy response**)

```lisp
- redisplay_internal (C function)                          24,042,398  54%
 + jit-lock-function                                       19,143,565  43%
   file-remote-p                                            3,518,162   7%
 + eval                                                       961,282   2%
 + tool-bar-make-keymap                                       314,911   0%
 + #<compiled 0x40c13c45>                                      15,840   0%
   kill-this-buffer-enabled-p                                  10,432   0%
 + zoom--handler                                                7,392   0%
 + keymap-canonicalize                                          5,280   0%
   menu-bar-update-buffers                                      5,280   0%
 + funcall                                                      1,056   0%
+ command-execute                                          19,438,599  44%
+ ucs-normalize-hfs-nfd-pre-write-conversion                  470,386   1%
+ timer-event-handler                                          20,064   0%
+ #<compiled 0x4061e247>                                       11,456   0%
+ undo-auto--add-boundary                                       7,392   0%
+ eldoc-schedule-timer                                          3,168   0%
  undefined                                                     1,506   0%
  ...                                                               0   0%

```

So I think the reason is that other minor modes or installed packages internally call `zoom` (such as `aggressive-indent-mode`) and the problem happens.

I'll try to detect the main reason of it.

**Comment by cyrus-and** [comment]
I think that the following may help you in figuring out what happens:

```elisp
(advice-add 'select-window :before (lambda (&rest ignore) (backtrace)))
```

**Warning:** very verbose output on `*Messages*`.

Similarly you can hook `window-size-change-functions` and `minibuffer-setup-hook` if needed.

**Comment by blue0513** [comment]
Thanks! 

hmm... when I type each char, this occurs every time and redisplaying internal.
<img width="811" alt="screen shot 2017-11-09 at 1 06 00" src="https://user-images.githubusercontent.com/8979468/32559485-9da8ce16-c4ea-11e7-935c-2afb56b40d6b.png">

**Comment by cyrus-and** [comment]
I don't know, try to disable `page-break-lines`, even though I've just tried it and seems to work fine.

Would it be possible for me to try your Emacs config?

**Comment by blue0513** [comment]
Unfortunately disabling `page-break-lines` does not solve the problem (I guess other packages call it internally)

Yes! I can share you my `.emacs.d` including `elpa/` and `init.el`.
But I don't have the repo on public services. Can I share them privately with you using e-mail or something ? If it is not good, I'll upload my `.emacs.d` to a public repository.

**Comment by cyrus-and** [comment]
Feel free to send me an e-mail.

**Comment by cyrus-and** [comment]
For the records: the problem was related to [`hiwin-mode`][1] which doesn't set the `NORECORD` option to `t` when selecting windows (`select-window`) for managing purposes; a PR is on the way.

[1]: https://github.com/tomoya/hiwin-mode
