### ISSUE TITLE
Trouble cloning

### ISSUE THREAD

**Issue by JohnLunzer** [cyrus-and/zoom#18]
You may want to check your repo permissions, I'm having trouble cloning.

**Comment by cyrus-and** [comment]
Wat?

**Comment by JohnLunzer** [comment]
just what I said, when I tried git clone I got an https error, but only for this repo. I tried to clone a couple other repos just a few minutes apart and they all cloned without issue.

**Comment by cyrus-and** [comment]
Since it's a pretty weird issue and the fact that you're able to comment here suggests that this is not a private repo... providing the command you used to clone and the error would be useful.

**Comment by JohnLunzer** [comment]
git clone https://github.com/cyrus-and/zoom.git

It may just be a transient server issue

**Comment by cyrus-and** [comment]
FWIW an anonymous clone works *here*.
