### ISSUE TITLE
Custom zoom levels per mode

### ISSUE THREAD

**Issue by JohnLunzer** [cyrus-and/zoom#19]
I use navi-mode a lot and I would like to always have it zoom to a "narrow" view. So basically it would be the opposite of what most people would want zoom for. Is this possible with zoom?

**Comment by cyrus-and** [comment]
Currently the specified dimension hints are respected even if they lead to a smaller window, provided that the target size is larger than the size after the balancing.

But you cannot specify hints for windows other than the currently selected one, at most you can ignore that buffer/mode, but see this [FAQ][1].

[1]: https://github.com/cyrus-and/zoom#why-windows-are-resized-even-when-they-are-ignored
