### ISSUE TITLE
helm flicker when typing 

### ISSUE THREAD

**Issue by neeasade** [cyrus-and/zoom#2]
Hi,

I experience flickering doubled buffer text whenever I type in a helm selection. 

I've currently got:

``` elisp
(setq zoom-size '(0.58 . 0.618))
(setq zoom-ignored-buffer-name-regexps '("^*helm" "^helm"))
```

Here is a webm of Helm m-x: https://u.teknik.io/d78Yn.webm

**Comment by cyrus-and** [comment]
Hi, I cannot reproduce this using my current setup. I acknowledge that it's important to ignore Helm but after that, I don't experience any flickering. Maybe this is not strictly related to Helm.

Are you able to reproduce this issue starting from `emacs -Q`? Alternatively, would it be possible for me to try your configuration?

Thanks.

**Comment by neeasade** [comment]
> Alternatively, would it be possible for me to try your configuration?

sure -- it's spacemacs, config [here](https://github.com/neeasade/dotfiles/tree/master/emacs), zoom enabled [here](https://github.com/neeasade/dotfiles/blob/master/emacs/.spacemacs.d/lisp/config.el#L20)

To reproduce, open a file with text in it (scratch has the same issue but doesn't show when empty), press space-space, type a bit, quit (doesn't happen first time) press space-space again, see the issue.

> Are you able to reproduce this issue starting from emacs -Q? 

I was not with Helm-M-x on the bottom, unsure quite how spacemacs does it from the top (which is what I have). Trying with:

``` elisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(package-initialize)
(package-install 'helm)
(package-install 'zoom)
  
(with-eval-after-load 'helm
      (setq helm-autoresize-min-height 10)
      (helm-autoresize-mode 1)
      )

(require 'zoom)
(require 'helm)
(setq zoom-size '(0.58 . 0.618))
(setq zoom-ignored-buffer-name-regexps '("^*helm" "^helm"))
(zoom-mode t)
```

**Comment by neeasade** [comment]
curiously, when in my setup I run helm from the bottom position, the helm buffer flickers and the others don't. https://u.teknik.io/rQ8fc.webm

**Comment by cyrus-and** [comment]
> sure -- it's spacemacs, config here, zoom enabled here

Something goes wrong when I try to clone your repo:

```
$ git clone --recursive https://github.com/neeasade/dotfiles
Cloning into 'dotfiles'...
remote: Counting objects: 7955, done.
remote: Compressing objects: 100% (81/81), done.
remote: Total 7955 (delta 57), reused 114 (delta 47), pack-reused 7811
Receiving objects: 100% (7955/7955), 2.77 MiB | 1.72 MiB/s, done.
Resolving deltas: 100% (3907/3907), done.
Submodule 'emacs/.emacs.d' (https://github.com/syl20bnr/spacemacs/) registered for path 'emacs/.emacs.d'
fatal: No url found for submodule path 'emacs/.spacemacs.d/layers/music' in .gitmodules
```

---

But starting from a vanilla Spacemacs I experience that flickering. Let me look into that...

**Comment by cyrus-and** [comment]
A trivial workaround seems to be setting `helm-full-frame` to `t`.

**Comment by cyrus-and** [comment]
I think I found a solution, please give it a try.

**Comment by neeasade** [comment]
https://github.com/cyrus-and/zoom/commit/52345c2dea4444e41fd6f2ee4733b16cfaa04f91 works great, thanks

**Comment by cyrus-and** [comment]
Awesome! Thanks for reporting this issue.
