### ISSUE TITLE
Creating windows with C-x 3 causes Emacs to freeze and hang

### ISSUE THREAD

**Issue by m-cat** [cyrus-and/zoom#21]
H-hi...

I have the following `zoom!` configuration:

```
;; Zoom!
(use-package zoom
  :config
  (zoom-mode t)
  (setf zoom-size '(0.52 . 0.55))
  )
```

Looks good, right? Well the problem is that creating windows with C-x 3 causes Emacs to freeze and hang. With `(80 . 0.55)` instead, this doesn't happen.

Perhaps related is the following: resizing the frame so that the widths of some windows are below `window-min-width` (which I set to 25) causes Emacs to freeze and hang. This doesn't happen without `zoom` enabled.

Let me know if there's anything you need from me to help debug this damned bug.

**Comment by cyrus-and** [comment]
Hi! This is weird, when a window is too small I get a message like:

    split-window: Window #<window 3 on issue> too small for splitting

In any case Emacs doesn't hang and freeze here.

Try running Emacs with the `-Q` option and tell me the what Emacs version you're using.
