### ISSUE TITLE
Dired-sidebar unusable with zoom enabled

### ISSUE THREAD

**Issue by 4goodapp** [cyrus-and/zoom#27]
I can't use Dired-sidebar when I have zoom enabled.

Edit:
When I have both enabled, If I focus on the tired-sidebar windows buffer by clicking on it, It focus there for like 200ms, then focus back to the previous window buffer. 
And after debugging, this happens only when I use zoom. if I delete the app, the issu disappear, and come back if I add zoom.

**Comment by cyrus-and** [comment]
`dired-sidebar` works fine here, *unusable* is not helpful in a bug report...

**Comment by 4goodapp** [comment]
@cyrus-and I just edit it.

**Comment by cyrus-and** [comment]
I'm unable to reproduce that, what version of Emacs are you using?

**Comment by 4goodapp** [comment]
Am using Emacs Version 26.3.

**Comment by cyrus-and** [comment]
Alright, I'm finally able to reproduce this, but only if I start  with `-Q`, i.e., my setup is not affected, let me debug...

**Comment by cyrus-and** [comment]
Weird the issue appears only in presence of scrollbars, it should go away if you disable them with:

```lisp
(custom-set-variables
 '(scroll-bar-mode nil))
```

**Comment by cyrus-and** [comment]
> it should go away

Not entirely true, it's almost unnoticeable but it's still there.

**Comment by cyrus-and** [comment]
Woah, I finally got this, the solution is:

```lisp
(custom-set-variables
 '(dired-sidebar-toggle-hidden-commands nil))
```

Basically the default value of the above variable is `'(balance-windows)` meaning that every time `balance-windows` is called (it is called by Zoom) the `dired-sidebar` window is destroyed and recreated, which in turn triggers a Zoom update and so on and so forth...

Let me know if this fixes your problem.

**Comment by 4goodapp** [comment]
Hello,
Sorry for taking this long to reply.
I just test again zoom but it just doesn't work anymore... Not sure why.
When I enable it and open let's say three windows, nothing happens when I switch between them. Any resize.

**Comment by cyrus-and** [comment]
> I just test again zoom but it just doesn't work anymore...

With and without `dired-sidebar`? Try with `emacs -Q` and install from there.

**Comment by 4goodapp** [comment]
With `Emacs -Q` on macOS, it only works when Emacs windows is small... like like half of the screen.

**Comment by cyrus-and** [comment]
I cannot reproduce it, it would be great if you could do a screencast and provide the Emacs version.

**Comment by 4goodapp** [comment]
When Emacs is in full screen, nothing happens, but when you resize it zoom works.
![zoom](https://user-images.githubusercontent.com/6249230/79615340-0efb1b80-80f2-11ea-9a49-43635c2c6d29.gif)

**Comment by cyrus-and** [comment]
Oh could it be that the value of `zoom-size` is small enough so that there's no need to zoom? Try increasing that value.

**Comment by 4goodapp** [comment]
It's working now. I removed all settings for zoom, delete my custom file and restart Emacs.
---

About the issue with dired-sidebar, after adding:
```lisp
(use-package dired-sidebar
  :custom
  (dired-sidebar-toggle-hidden-commands nil)
...
```
like you suggested above, it's working fine.

**Comment by cyrus-and** [comment]
Glad to hear that! :)

**Comment by 4goodapp** [comment]
btw, Are you on Discord?

**Comment by cyrus-and** [comment]
I am actually, but drop me an email or find me there.

**Comment by 4goodapp** [comment]
Where can I drop an Emails :) ?

**Comment by cyrus-and** [comment]
See my website in the profile page.

**Comment by 4goodapp** [comment]
OK, I think we delete the noise now :)
