### ISSUE TITLE
Org Capture Frame is showing only half 

### ISSUE THREAD

**Issue by dragarok** [cyrus-and/zoom#28]
![2020-04-23-080458_841x351_scrot](https://user-images.githubusercontent.com/36977610/80051997-4b3adb80-8539-11ea-9be8-c887c10f8a46.png)
I am using doom emacs and my capture frame only shows half of the choices.

**Comment by cyrus-and** [comment]
It is not clear if the `*Org Select*` window is zoomed or not from your screenshot. Works fine here. In any case that window is not scrollable AFAIK and if there are many choices some will eventually fall off screen.

**Comment by dragarok** [comment]
![2020-04-23-141023_1139x1041_scrot](https://user-images.githubusercontent.com/36977610/80076690-42173200-856c-11ea-9b11-b4076fc00a27.png)
![2020-04-23-140959_1139x1035_scrot](https://user-images.githubusercontent.com/36977610/80076694-43485f00-856c-11ea-817f-64000c4431bf.png)
So, it looks kinda like this when zoom mode is enabled vs zoom mode disabled. I would be grateful even if I can workaround with something in my config file.

**Comment by cyrus-and** [comment]
Does this help?

```lisp
(custom-set-variables
 '(temp-buffer-resize-mode t))
```

It looks like the Org Capture list appears in the minibuffer to you, is this the case? It opens in a regular window by default:

![2020-04-23-103043_743x486_scrot](https://user-images.githubusercontent.com/1660263/80077280-92cb6280-854d-11ea-94d7-4bf305a41b6c.png)

**Comment by dragarok** [comment]
I just made a popup rule for Org select frame and it worked. Thanks for this amazing package here.

**Comment by cyrus-and** [comment]
Glad you fixed it!
