### ISSUE TITLE
zoom-mode caused weird behavior in image-mode

### ISSUE THREAD

**Issue by stardiviner** [cyrus-and/zoom#31]
When I use `[C-x C-f]` to open `filename.jpg` or open jpg image file from Dired. The buffer displays empty. But open `filename.png` is fine. But in opened jpg image buffer, I press `M-<` , the image is displayed. I guess the image is correctly opened and displayed, just `zoom-mode` caused point offset position. Then I verified this bug with minimal Emacs config `emacs -q`.

**Comment by cyrus-and** [comment]
It should be fixed now, please give it a try, thanks!

**Comment by stardiviner** [comment]
Really quick fix! Thanks! cyrus-and
