### ISSUE TITLE
Excluded buffer weirdness

### ISSUE THREAD

**Issue by loafofpiecrust** [cyrus-and/zoom#33]
I'm using doom emacs on the `native-comp` branch. Maybe that means all bets are off, but I'll give this a shot since the latest `gccemacs` updates indicate that compatibility is almost 100%.

If I enable `zoom-mode` and add `helpful-mode` and `"^*mu4e"` to the exclusion list, the result is that most windows zoom except `mu4e` and `helpful` buffers. However, if a `helpful-mode` buffer is open, I can't open other help buffers in the same window. 

I get this error:
```
Error during redisplay: (#[128 "\300\302\"\300\301\"\210\207" [apply zoom--handler #[128 "\300\301\"\210\300\302\"\207" [apply redisplay--pre-redisplay-functions ignore nil] 4 nil nil] nil] 5 nil nil] t) signaled (wrong-type-argument window-valid-p #<window 24607>)
```

Relatedly, mu4e buffers seem to get resized to exactly half the frame even though they should be left alone.

**Comment by cyrus-and** [comment]
What about `native-comp` with vanilla Emacs (i.e., no Doom)?
