### ISSUE TITLE
Let zoom support ignore company-box

### ISSUE THREAD

**Issue by stardiviner** [cyrus-and/zoom#34]
Hi @cyrus-and , nice to see you again.

When I complete code with [company-box](https://github.com/sebastiencs/company-box), I found it's slow, Then I profiled it. Found when company-box popup, zoom is also invoked. I hope zoom can ignore company-box. It take many resources. Especially slow down the company completion popup which brain feels more sensitive.

I try to check out company-box whether has buffer name of something else so that I can apply zoom filters. But I have not found clue. Then I check out `zoom-handler`. I think it should detect whether in company-box frame, if yes, then don't execute zoom.

**Comment by cyrus-and** [comment]
Hey @stardiviner!

According to the [source code](https://github.com/sebastiencs/company-box/blob/be37a9a30dc112ab172af21af694e2cb04a74f85/company-box.el#L319-L322):

```lisp
(defun company-box--get-buffer (&optional suffix)
  "Construct the buffer name, it should be unique for each frame."
  (get-buffer-create
   (concat " *company-box-" (company-box--get-id) suffix "*")))
```

Have you tried to ignore that buffer name? For example with (mind the space before `*`.):

```lisp
(custom-set-variables
 '(zoom-ignored-buffer-name-regexps '("^ *company-box-")))
```

But, apparently Zoom is not triggered by company-box, at least not on my setup, for example you can check that by placing a `(message "ZOOM")` at the top of the `zoom-update` function and then triggering the Company popup.

**Comment by stardiviner** [comment]
Hi, @cyrus-and , I added `(message "ZOOM")` in `zoom-update`. Confirmed company-box does not triggered zoom.
I supposed zoom is triggered by ivy invoked profiler-report command.
And thanks for your hints. 😃

**Comment by cyrus-and** [comment]
You're welcome! Feel free to add details if you come up with something new.
