### ISSUE TITLE
How do I zoom to resize when frame is less than a particular width and/or height?

### ISSUE THREAD

**Issue by atanasj** [cyrus-and/zoom#35]
What I want is for `zoom` to kick in when I have less screen real estate (my laptop in particular). I have the following config: 

```elisp
(use-package! zoom
  :hook (doom-first-input . zoom-mode)
  :config
  (defun size-callback ()
    "Set the zoom-size by frame width"
    (cond ((< (frame-pixel-width) 1280) '(0.618 . 0.618))
          (t                            '(0.5 . 0.5))))
  (setq zoom-size 'size-callback
        ;; zoom-size '(0.618 . 0.618)
        zoom-ignored-major-modes '(dired-mode vterm-mode help-mode helpful-mode rxt-help-mode help-mode-menu org-mode)
        zoom-ignored-buffer-names '("*doom:scratch*" "*info*" "*helpful variable: argv*")
        zoom-ignored-buffer-name-regexps '("^\\*calc" "\\*helpful variable: .*\\*")
        zoom-ignore-predicates (list (lambda () (< (count-lines (point-min) (point-max)) 20))))
  )
```

This works as you would expect, but only when there are 3 or more frames, regardless of the frame width or height. 

Is what I want possible? If so, if you could help me configure this that would be greatly appreciated.

**Comment by atanasj** [comment]
I want to disable Zoom on larger screen / frame sizes. So, on larger screens, if I was to have more frames (e.g., treemacs, and two additional frames oriented in vertical splits), then the two non-treemacs frames would be adjusted by Zoom (if they were below a certain threshold), otherwise they would remain at .50 split as standard.

**Comment by cyrus-and** [comment]
If the window to be zoomed is already big enough then nothing is done, so maybe this will be enough:

```lisp
(defun size-callback ()
  "Set the zoom-size by frame width"
  (cond ((< (frame-pixel-width) 1280) '(0.618 . 0.618))
        (t                            '(0 . 0)))) ; just balances the windows, do not zoom
```

**Comment by atanasj** [comment]
Okay, that seems to have fixed the issues. For the record, I actually had to change the `frame-pixel-width` value on my MBP late-2013 to get it to work as I wanted:

```elisp
(defun size-callback ()
  "Set the zoom-size by frame width"
  (cond ((< (frame-pixel-width) 1380) '(0.618 . 0.618))
        (t                            '(0 . 0)))) ; just balances the windows, do not zoom
```

Thanks for your help.
