### ISSUE TITLE
flickering on ess-display-help-on-object

### ISSUE THREAD

**Issue by atanasj** [cyrus-and/zoom#36]
When calling help on an object in an `ess` buffer (via `ess-display-help-on-object`), I get some weird flickering in the Emacs window. Not sure how else to describe it, but I see there have been some similar issues experiences previously (#1 and #2). 

I'm on:

```bash
Doom v2.0.9 (HEAD -> develop 315ae1624 2020-11-17 12:46:10 -0500)
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H15
```

Any help is greatly appreciated. Thanks. 

### EDIT

Actually, this seems to also be in other help buffers too... not at noticeable as in `ess` (which I use regularly), but still there.

**Comment by cyrus-and** [comment]
I'm having trouble reproducing complex GUI scenarios like this since Emacs stopped working on macOS Big Sur. I'll try later on...

**Comment by atanasj** [comment]
Okay, no worries @cyrus-and. Thanks for your responsiveness and help.

**Comment by cyrus-and** [comment]
It seems I cannot reproduce this, can you give me more information about it? A minimal setup would be great. No flickering in the below scenario.

<img width="1552" alt="Screenshot 2020-12-23 at 10 22 08 PM" src="https://user-images.githubusercontent.com/1660263/103037910-4ec1af00-456d-11eb-93d4-d68f82530ae3.png">

It could also be possible that the #37 fixed this issue too.
