### ISSUE TITLE
i have serious issue with vterm

### ISSUE THREAD

**Issue by vijaypanchalr3** [cyrus-and/zoom#39]
https://user-images.githubusercontent.com/72692300/147858128-baf4bc8e-4475-46f8-a4ff-753e74295d69.mp4

**Comment by cyrus-and** [comment]
I'm not sure it's just `vterm`, I use it every day and I don't have that issue. Please try to come up with a minimal init file that reproduces that issue, something like:

```el
(setq custom-file "/dev/null")

(package-initialize)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))

(package-install 'zoom)
(package-install 'vterm)

(custom-set-variables
 '(zoom-mode t))
```
