### ISSUE TITLE
`balance-windows` calls changes layout of ignored windows (Treemacs) in an undesirable way

### ISSUE THREAD

**Issue by not-in-stock** [cyrus-and/zoom#40]
Hello,
First of all, thank you for your work providing a decent alternative to a `golden-ratio-mode`.
Here's my case:
In my `init.el` I've added a list of the following `zoom` options
```elisp
(with-eval-after-load 'zoom
    (setq zoom-size '(0.6 . 0.6)
          zoom-ignored-major-modes '(treemacs-mode))
```
But I haven't achieved the desired effect of keeping  `treemacs` window ignored once the zoom mode is turned on.
However, I've taken a look into a code of `zoom.el` and found out that on every call of `zoom--update` it balances the window with `balance-windows`, and since `zoom` reacts on every window change it also keeps rebalancing `treemacs` window every time keeping it undesirably large. I'm not entirely sure if it's essential for a `zoom` to call `balance-windows` in `zoom--update` and `zoom--off` in order to work properly, but I've made a couple of experiments in the fork and it looks like that without these calls it works just as I expected - everything is affected by `zoom` but `treemacs` keeps the initial size.
Well, is it then possible to either make `balance-windows` calls optional or to forward the same set of ignoring conditions that `zoom` accepts?

I suppose that since `balance-windows` accepts the `window-or-frame` optional argument, `window-list` can be called on an every passing `frame`, and each `buffer` of the `(window-buffer window)` call can probably be tested against something similar to `zoom--window-ignored-p`.

**Comment by cyrus-and** [comment]
> Well, is it then possible to either make `balance-windows` calls optional or to forward the same set of ignoring conditions that `zoom` accepts?

Not calling `balance-windows` causes an uneven window layout (see #7).

Besides, I don't seem to experience any issues with treemacs (GNU Emacs 29.0.50). I'm using the following `.emacs`:

```el
(setq custom-file "/dev/null")

(package-initialize)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))

(package-install 'zoom)
(package-install 'treemacs)

(custom-set-variables
 '(zoom-mode t))

(treemacs)
```

Can you help me to reproduce your issue?
