### ISSUE TITLE
woes with helm and which-key

### ISSUE THREAD

**Issue by LevPetrovitch** [cyrus-and/zoom#41]
This is more of a feature request than anything else, since the behavior that is annoying me is `zoom--update` working as expected (and this is way I dispensed myself from filling the issue template)

I use which-key and helm, both of which create temporary windows with the _right_ dimensions (for an opportune definition of right). I was able to make zoom ignore them by defining an opportune predicates but, as expected, zoom balances them an the result  is *not nice*™.  

Workaround like the one suggested in the FAQ for `imenu` can't be used, because both packages resize their own window when the content changes, so making them fixed-size is not an option.

As I see it there are two possible solutions to this problem:

1. add a customization that allows to disable windows balancing altogether
2. add a way to specify that some windows should not balanced (i.e. they should be considered as of fixed size as far as ``balance-windows` is concerned 

While the first solution is easy to implement (I may submit a pull-request if you're interested) it is surely an overkill. I'm thinking about a way to implement the second solution but, for now, I'm not even sure it would work. Should I find a way to implement it I'll post a pull request in a follow-up to this issue (If you're interested, that is).

**Comment by cyrus-and** [comment]
> Workaround like the one suggested in the FAQ for `imenu` can't be used, because both packages resize their own window when the content changes, so making them fixed-size is not an option.

This case is in no way different from all the others, and the issue is always the same: whoever manages the window does not fix its size afterwards. For example the following workaround seems to work with which-key:

```elisp
(defun my/which-key-fix (original window &rest args)
  ;; only for the which-key window
  (when (eq (window-buffer window) which-key--buffer)
    ;; unfix the window size
    (with-selected-window window
      (setq window-size-fixed nil))
    ;; call the original fit-window-to-buffer
    (apply original window args)
    ;; fix the window size
    (with-selected-window window
      (setq window-size-fixed t))))

(advice-add 'fit-window-to-buffer :around 'my/which-key-fix)

;; (advice-remove 'fit-window-to-buffer 'my/which-key-fix)
```

> 1. add a customization that allows to disable windows balancing altogether

Zoom without window balancing is just broken, I'm not sure if I feel like implementing it.

> 2. add a way to specify that some windows should not balanced (i.e. they should be considered as of fixed size as far as ``balance-windows` is concerned

This is what all the workaround so far are doing, but this is really something modes developers are in charge of.

**Comment by LevPetrovitch** [comment]
Thank you for your suggestion. I was able to extend it to handle helm buffers too by doing the following:
```el
  (defun my/fix-buffer-for-zoom (original window &rest args)
	(let ((win (or window (frame-selected-window))))
	  (when (or (and (bound-and-true-p which-key--buffer)
					 (eq (window-buffer win) which-key--buffer))
				(with-selected-window win (bound-and-true-p helm-alive-p)))
		(with-selected-window win
		  (setq window-size-fixed nil))
		(apply original win args)
		(with-selected-window win
		  (setq window-size-fixed t)))))
  (advice-add 'fit-window-to-buffer :around 'my/fix-buffer-for-zoom)
```
The `let` is needed because helm calls `fit-window-to-buffer` with no parameters.

**Comment by cyrus-and** [comment]
Great, thanks for sharing!
