### ISSUE TITLE
Window sizes change when dropping into minibuffer

### ISSUE THREAD

**Issue by dieggsy** [cyrus-and/zoom#8]
When using e.g. `eval-expression`, windows change size (they get balanced). Is this intended behavior? It's pretty distracting as when I go to search a buffer with `evil-ex-search-forward`, the window sizes change.

**Comment by cyrus-and** [comment]
They change because the selected window becomes minibuffer ( d36b9b5892615c3937f4a4d4bd9242f870c4bc50). I'll see if I can fix the issue described in that commit and make it an optional behavior.

Note: this doesn't happen with `isearch` or `ispell`.

**Comment by cyrus-and** [comment]
OK, I introduced `zoom-minibuffer-preserve-layout` in 633046edbc42502fd93464f91c43eab75d7d5dd3, it defaults to `t` so it should just work for you.

**Comment by dieggsy** [comment]
Great! Thank you!
