### ISSUE TITLE
ispell and hydra windows are getting resized

### ISSUE THREAD

**Issue by WolfeCub** [cyrus-and/zoom#9]
When using `ispell` and `hydra` the windows are resized like so:

![hydra](https://u.teknik.io/fwZTI.png)

![ispell](https://u.teknik.io/F7KTp.png)

Using `zoom-ignored-buffer-names` doesn't seem to solve the issue nor does `zoom-ignore-predicates`. I know that setting `hydra-lv` to `nil` will fix the issue for hydra but ideally I'd like to be able to properly exclude windows.

**Comment by cyrus-and** [comment]
I cannot reproduce the `ispell` part (I will try `hydra` later), can you try starting `emacs` with `-Q` and then loading Zoom?

**Comment by cyrus-and** [comment]
Actually `hydra` too works fine, I suspect that you're using an old version of Zoom. 52345c2dea4444e41fd6f2ee4733b16cfaa04f91 fixed the issue you're experiencing.

**Comment by WolfeCub** [comment]
The newest version of `zoom` doesn't fix `hydra`. Do you have `hydra-lv` set to `t`?

I'll check ispell when I get home from work.

**Comment by cyrus-and** [comment]
> Do you have hydra-lv set to t?

Yes, I start Emacs with `-Q` then I install `zoom` and `hydra`; I'm using all the defaults and trying ["The impressive-looking one"][1]. The result is similar to that screenshot, in particular the height is correct.

[1]: https://github.com/abo-abo/hydra#the-impressive-looking-one

**Comment by noctuid** [comment]
Yes lv works fine for me too on the newest version of zoom.

**Comment by cyrus-and** [comment]
@noctuid thanks, do you have any problems with `ispell`?

@WolfeCub did you have the chance to try it?

**Comment by noctuid** [comment]
I don't normally use ispell, but I checked just now, and ispell buffers are still altered by zoom for me.

**Comment by WolfeCub** [comment]
Hydra works fine for me with `emacs -Q` so I guess I'll need to hunt down what's conflicting with it.

Ispell is still resized for me though.

**Comment by cyrus-and** [comment]
I still cannot reproduce this with `ispell`, that's weird:

1. `emacs -Q`;
2. `M-x load-file RET /path/to/zoom.el`;
3. `M-x zoom-mode`;
4. write something wrong in `*scratch*`;
5. `M-$`.

I obtain:

![2017-10-20-220130_955x1062_scrot](https://user-images.githubusercontent.com/1660263/31839637-4608df5a-b5e2-11e7-86f3-9ef422bbdd64.png)

**Comment by WolfeCub** [comment]
Not sure if it makes a difference but I've been calling by doing `M-x ispell` rather than `M-$`.

**Comment by cyrus-and** [comment]
OK I can consistently reproduce this with Emacs 24 but not with Emacs 26 that I'm currently using.

**Comment by noctuid** [comment]
I'm using emacs 26 as well, and there is no problem if I use `emacs -Q` (only with my config).

**Comment by WolfeCub** [comment]
Same thing here

**Comment by cyrus-and** [comment]
So unless there are further details I'm going to mark this as irreproducible. Feel free to update if you come up with something relevant. Thanks.
